### ISSUE TITLE
[Bug] Chunk loaders seem to not load a players Chunks until they join the server

### ISSUE THREAD

**Issue by vaaski** [SuperMartijn642/ChunkLoaders#115]
**Version Info**
- Minecraft, 1.20.1
- Chunk Loaders, Fabric

**Are you using OptiFine?:**
Hell nah

**Description of the Bug**
I have a friend who placed most of the chunkloaders in our world, however, when we restart the server they seem to be not loaded when just I join. Setting the `inactivityTimeout` to `-1` also doesn't change that.

**Steps to Reproduce**
Player A loads a couple chunks, server restarts, player B joins and the chunks loaded by player A do not get loaded.

**Screenshots**
![image](https://github.com/SuperMartijn642/ChunkLoaders/assets/17879327/14d80a9b-1188-4f64-9bf9-143797fbc3a9)
> player A chunks shown in grey

**Comment by Lemopav** [comment]
i'll just confirm. using this mod with create on version 1.19.2 on Fabric. Only after the owner of the chunkloader joins the server after a server restart, the chunkloader actually works. otherwise, in this case, the train that waits until it is fully unloaded just stands inside that unloaded chunk and does nothing because it can't unload.

edit: i'm using modversion 1.2.8a, i'll try 1.2.8, maybe it'll change.
edit2: Sorry, should've tested that before. BUT still nothing changed. now using modversion 1.2.8 still same issue.

**Comment by SuperMartijn642** [comment]
I cannot reproduce the issue. After stopping and starting the server again, previously loaded chunks are immediately loaded again:

https://github.com/SuperMartijn642/ChunkLoaders/assets/12382965/b9398316-f249-4022-a4b9-bf1a6e39dcb3

(The video was tested on Fabric 1.20.1 with Chunk Loaders 1.2.8a.)

Are you using the default config settings (at `configs/chunkloaders-common.toml`) for Chunk Loaders?
Are there any other mods needed to reproduce the issue?
Any specific steps to reproduce the issue?
