### ISSUE TITLE
Chunk env tick without loaded check

### ISSUE THREAD

**Issue by someaddons** [SuperMartijn642/ChunkLoaders#17]
Version Info

Minecraft, 1.16.5
Chunk Loaders, chunkloaders-1.1.7-mc1.16.5.jar

I think the enviroment ticking here probably should have a chunk is loaded check first, afterall this may not be the only mod using some chunkloading mechanics and thus its not guaranteed to exist. If it does not exist this would rapidly reload the chunk and cause a decent amount of lag.

https://github.com/SuperMartijn642/ChunkLoaders/blob/b7d10cebfbc8e45b89341511d7f63d183bbb8e39/src/main/java/com/supermartijn642/chunkloaders/ChunkLoaderUtil.java#L151

**Comment by SuperMartijn642** [comment]
All chunks that are being ticked are chunks that have been force loaded by chunk loader blocks.
Since the chunkloading tickets are registered with this mod, other mods shouldn't be able to cancel that.
So, I think all the chunks that I call `tickEnvironment(Chunk, int)` on should already be loaded and it isn't an issue.

**Comment by someaddons** [comment]
Ye but you're not accounting for other mods which also do the same and can unforce the chunk aswell, its not a closed world afterall

**Comment by SuperMartijn642** [comment]
No longer relevant as of Chunk Loaders 1.2.0, so I'll close the issue.
