### ISSUE TITLE
[Question] AI and Falling

### ISSUE THREAD

**Issue by isaaclepes** [SuperMartijn642/ChunkLoaders#47]
**Question**
I created a zombie villager system that uses a chunk loader to keep it active.  It seems to work fairly well, except for 2 things:

1.) Minecarts sent to pickup a villager often come through empty unless I visited the villager breeder (also using a chunk loader) recently.
2.) My minecart system drops a minecart with villager down to a zombie that is waiting to turn them. However, if it has been several minutes since I visited the zombie chamber, the minecart seems to be floating above the drop until the player visits, whereby it drops down properly.

So my question is twofold:
1.) Can entities 'fall' in chunk-loaded chunks?
2.) Is there some collision/AI issue, etc. that would explain why the minecart can't pickup a villager when the player has been absent for a few minutes?

**Comment by SuperMartijn642** [comment]
> 1.) Can entities 'fall' in chunk-loaded chunks?

As far as I know, yes, however, these are just vanilla mechanics. Chunk Loaders simply keep chunks loaded just like the vanilla `/forceload` command (plus random block ticks).

> 2.) Is there some collision/AI issue, etc. that would explain why the minecart can't pickup a villager when the player has been absent for a few minutes?

I know in Minecraft 1.18 a new feature was introduced so entity logic will be 'paused' if the entity is not within a certain range of the player. I don't exactly know how this relates to chunk loading though, so that might be what you are experiencing if you are playing on Minecraft 1.18.

Anyways, Chunk Loaders just does what the vanilla `/forceload` command does, plus random ticks on top of that. If something works with `/forceload`, but not with Chunk Loaders, it is likely an issue with Chunk Loaders. If something does also not work with `/forceload`, it likely depends on more than just the chunk being loaded. I might be able to add such cases as a feature to Chunk Loaders, but that depends on how performance intensive it is and how much work it would be for me to create and maintain.

**Comment by isaaclepes** [comment]
Yes, this is 1.18.1.  Some things work fine, such as sending a minecart through (without any falling), Create mod's pulse repeaters and extenders still hold their timings, etc.

I was wondering if your scarecrow mod could be used here as a fake player, but I am not sure if that is solely for spawners.

**Comment by SuperMartijn642** [comment]
The scarecrows are not actually fake players. They specifically keep spawners activated and allow passive mob spawning, so in this those won't help.

**Comment by isaaclepes** [comment]
I think I figured out the issue.  OptiFine. It was causing issues with Little Logistics' chunk loader, as well as Create Chunkloading.  Turns out it changes how chunks are loaded by default. I solved by disabling Lazy Chunk Loading and Smooth World settings in OptiFine as suggested in Little Logistics' issue tracker.

https://github.com/MuradAkh/LittleLogistics/issues/53

**Comment by SuperMartijn642** [comment]
Ah I see, yet another thing broken by OptiFine. Thank you for the reply 🙂
