### ISSUE TITLE
[Question] Is it possible to run Chunk Loader 1.2.2 on Minecraft 1.18.2 Forge 40.1.20?

### ISSUE THREAD

**Issue by Accelerator-Li** [SuperMartijn642/ChunkLoaders#65]
My other mods can only run on Forge 40.1.20 and below.

Is there any reason why Chunk Loader cannot use Forge 40.1.20?

New version of Forge fix some bugs or it's APIs has been changed?

**Comment by SuperMartijn642** [comment]
Forge 40.1.58 fixes a bug in the Forge chunk loading system, where chunks loaded through it would not get ticked. The fix is essential for the functionality of Chunk Loaders.

As a side note, after the first recommended build (40.1.0 for 1.18.2) Forge will not have any breaking changes, so mods made for a version after 40.1.0 should work on any newer Forge version.
