### ISSUE TITLE
[Feature] Please add a mention of the requiered lib  on the mod description

### ISSUE THREAD

**Issue by ghost** [SuperMartijn642/ChunkLoaders#70]
The game crashes on load. happens when minecraft is heavily modded, missing lib message doens't appear anymore, it just crashes. and removing everything to see what is requiered resets all my keybinds.

![Captura de Tela (212)](https://user-images.githubusercontent.com/71791383/192615643-51eed03f-f66a-4b07-90b6-0db0bdc6b126.png)

**Comment by SuperMartijn642** [comment]
You literally shared a screenshot if it telling you that chunk loaders requires my core and config library 🤔 Why would you need to 'remove everything to see what is required'?

---

Apart from that, both CurseForge and Modrinth already show the required dependencies.

On CurseForge you can click on the 'relations' tab to see the dependencies across all files:
![image](https://user-images.githubusercontent.com/12382965/192629623-e378c7e3-fb00-4625-b1fa-1325530380d5.png)
Or you can click on a specific file to see which dependencies that file has:
![image](https://user-images.githubusercontent.com/12382965/192629798-9f0b56c4-7450-4a71-b161-671d267d4ce3.png)

On Modrinth you can see the dependencies for a file when you click on it:
![image](https://user-images.githubusercontent.com/12382965/192630041-e14b3e68-268a-487d-a2a2-c891ae62b81b.png)

---

I will not add the dependencies to the main description page because
1) CurseForge and Modrinth already show the dependencies.
2) The dependencies heavily depend on which version of Minecraft and which version of Chunk Loaders you want to use.
