### ISSUE TITLE
[Bug] Cannot assign chunks to be loaded on basic loader

### ISSUE THREAD

**Issue by vico93** [SuperMartijn642/ChunkLoaders#84]
**Version Info**
- Minecraft, 1.19.4
- Chunk Loaders, 1.2.3a-fabric-mc1.19

**Are you using OptiFine?:** No, but i'm using Sodium

**Description of the Bug**
Basically, i added the mod to my modpack, loaded an existent world, but when i placed a basic chunkloader and tried to assign a chunk to be loaded, the game got a heavy lag for a while, and when resumed running, no chunk was selected.
After loading the game i checked the [log](https://gist.github.com/vico93/705737435f4ca39841bcb798b19735df) and nothing was abnormal on that.

What's happening?

**Comment by SuperMartijn642** [comment]
Thank you for the report.
I found that the load level was incorrect when loading a chunk. I gave a value of 31, however vanilla subtracts the given value from 33, so instead of the chunks having a load level of 31, they had a load level of 2. Fixing that seemed to get rid of the lag when loading a chunk.

From my testing there was only a small lag spike when loading a chunk, so I am not completely sure if that was the issue you were running into. Could you check if it is fixed now with version 1.2.3b?

**Comment by LakshayGMZ** [comment]
> Thank you for the report. I found that the load level was incorrect when loading a chunk. I gave a value of 31, however vanilla subtracts the given value from 33, so instead of the chunks having a load level of 31, they had a load level of 2. Fixing that seemed to get rid of the lag when loading a chunk.
> 
> From my testing there was only a small lag spike when loading a chunk, so I am not completely sure if that was the issue you were running into. Could you check if it is fixed now with version 1.2.3b?

Hi, mod for forge 1.19.4 is out? it seems to download 1.19.3 forge in 1.19.4 section of curseforge. I tried that but no recipe appeared nor it is crafting

**Comment by SuperMartijn642** [comment]
@LakshayGMZ please don't post on a random issue.

**Comment by LakshayGMZ** [comment]
Sorry, it was a quick question so didn't bother making issue for that.
Could you please !?
